irf_powerfft: Cleanup and reorg before bugfixing
Should not contain any functional changes.
Exception: select_data instead of irf_tlim which should/could represent a
minor bugfix.

Nested functions-->local functions
Variable renaming etc.

modified:   irf/irf_powerfft.m